name: example-environment
channels:
  - anaconda
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - pip:
    - jupyter_contrib_nbextensions
    - fileupload  
